### ISSUE TITLE
JavaScript web crowd simulator

### ISSUE THREAD

**Issue by Jacq** [aelse/python-crowd#30]
Hi,

I found this repo quite valuable to built, during the past months, a JavaScript crowd simulator. Just want to thank the python-crowd collaborators for your work. You can find my implementation at https://github.com/Jacq/crowd-sim
Cheers,
Jacq

**Comment by aelse** [comment]
Hi,

This is a client to a user account management tool named Crowd. It doesn't actually have anything to do with crowd simulation. I think you've included us by accident in your references list. It's nice to get good feedback but I don't think we can claim any credit for helping you write your sim.

**Comment by Jacq** [comment]
Right sorry for the noise.!
I messed your references, I landed in your repo many times while looking for https://github.com/makokal/crowdsim that is the one related a python crowd simulator :).
